site_name: BYO Server
site_url: https://vexit.github.io/byoserver
theme:
  name: material
  custom_dir: overrides  # <--- THIS tells MkDocs to check your "Kill" file overrides/partials/build.html which is supposed to remove the "Made with MkDocs" line
  palette:
    - scheme: slate      # The Dark Background
      primary: green     # The Header/Sidebar color
      accent: green      # The Link/Button color
  features:
    - content.code.copy  # <--- THIS adds the One-Click Copy button
  hide:
    - generator # <--- THIS removes the "Made with Material for MkDocs" line
    
extra_css:
  - stylesheets/extra.css  # <--- THIS removes the "Made with Material for MkDocs" line

copyright: "Copyright &copy; 2026 VEXIT &reg;, Tomorrow is Today &trade;, www.vexit.com"

markdown_extensions:
  - admonition  # <--- This is what makes the !!! danger box work
  - pymdownx.details #  Allows you to create clickable "Expand/Collapse" boxes (useful for long logs or extra tips).
  - pymdownx.superfences #  It allows you to put your code inside those triple backticks (```) so they render beautifully.
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  # social:  # Commented out - website not ready yet
  #   - icon: fontawesome/solid/globe
  #     link: https://www.vexit.com
  social_cards:
    image: images/social-cover.jpg # This tells sites what image to use when sharing the link on social media
  # This section handles the link preview
  description: "Build your own Linux server from scratch. A Sovereign Systems Development guide to self-hosting web, database, and mail servers."
  # image: images/cover.jpeg  # Link preview image for social media
 
# This is the pro way to hide the generator if the simple 'hide' fails
extra_javascript:
  - https://unpkg.com

nav:
  - Home: index.md
  - Core Concepts (Bash/CLI): 0.1_File_System_Basics_with_Bash.md
  - Linux Permissions Reference: 0.2_Linux_Users_Groups_and_Permissions_Reference.md
  - "Choose Your Server Setup":
      - Server Setup Overview: 1_SetUpServer_Overview.md
      - Home Server (Ubuntu): 1_SetUpServer_HomeServer_Ubuntu.md
      - Home Server (Raspberry Pi): 1_SetUpServer_HomeServer_RaspberryPi.md
      - Home Server (Linux Mint): 1_SetUpServer_HomeServer_LinuxMint.md
      - VPS / Hosting Provider: 1_SetUpServer_VPS.md
  - Web Server (Nginx/Apache): 2_WebServer_Nginx_Apache.md
  - App Deployment (.NET/Angular): 3_WebApp_NetCore_Angular.md
  - Task Automation (Cron Jobs): 4_Cron_Jobs.md
  - Database (PostgreSQL): 5_Database_PostgreSQL.md
  - Mail Server (Postfix/Dovecot): 6_MailServer_Postfix_Dovecot_Thunderbird.md


